server:
  port: 8080

spring:
  application:
    name: egdeserver

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaltZone: http://localhost:8761/eureka
